import type { Metadata } from "next"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { AlertTriangle, Info, Shield, Zap } from "lucide-react"

export const metadata: Metadata = {
  title: "Disclaimer - Crea8Tools | AI Content Usage Guidelines",
  description:
    "Important disclaimer about AI-generated content from Crea8Tools. Understand the limitations and proper usage of our AI writing tools.",
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen py-20">
      <div className="container mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-foreground mb-4">Disclaimer</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Important information about AI-generated content and service limitations
          </p>
          <p className="text-sm text-muted-foreground mt-2">Last updated: January 2025</p>
        </div>

        <div className="space-y-6">
          <Card className="border-amber-200 bg-amber-50 dark:border-amber-800 dark:bg-amber-950">
            <CardHeader>
              <CardTitle className="flex items-center gap-2 text-amber-800 dark:text-amber-200">
                <AlertTriangle className="h-5 w-5" />
                AI-Generated Content Notice
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-amber-700 dark:text-amber-300 text-sm">
                All content generated by Crea8Tools is produced by artificial intelligence and should be reviewed,
                fact-checked, and edited before use. AI-generated content may contain inaccuracies, biases, or
                inappropriate material.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Info className="h-5 w-5" />
                Content Accuracy
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground text-sm">
                While our AI tools strive to generate helpful and relevant content, we cannot guarantee the accuracy,
                completeness, or reliability of any generated material. Users should:
              </p>
              <ul className="space-y-2 text-muted-foreground text-sm ml-4">
                <li>• Verify all facts and claims in generated content</li>
                <li>• Check for potential copyright or trademark issues</li>
                <li>• Ensure content complies with applicable laws and regulations</li>
                <li>• Review content for appropriateness and brand alignment</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="h-5 w-5" />
                Limitation of Liability
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground text-sm">
                Crea8Tools and its operators shall not be liable for any direct, indirect, incidental, special, or
                consequential damages resulting from:
              </p>
              <ul className="space-y-2 text-muted-foreground text-sm ml-4">
                <li>• Use of AI-generated content without proper review</li>
                <li>• Inaccuracies or errors in generated material</li>
                <li>• Copyright or intellectual property infringement</li>
                <li>• Business losses or damages from content usage</li>
                <li>• Service interruptions or technical issues</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Zap className="h-5 w-5" />
                Service Availability
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground text-sm">
                Our services are provided "as is" and "as available." We do not guarantee:
              </p>
              <ul className="space-y-2 text-muted-foreground text-sm ml-4">
                <li>• Continuous, uninterrupted service availability</li>
                <li>• Error-free operation of our tools</li>
                <li>• Compatibility with all devices or browsers</li>
                <li>• Permanent storage of generated content</li>
                <li>• Specific response times or performance levels</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Professional Advice</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground text-sm">
                Content generated by our AI tools should not be considered as professional advice in legal, medical,
                financial, or other specialized fields. Always consult with qualified professionals for matters
                requiring expert guidance.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>User Responsibility</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground text-sm">By using Crea8Tools, you acknowledge that:</p>
              <ul className="space-y-2 text-muted-foreground text-sm ml-4">
                <li>• You are solely responsible for how you use generated content</li>
                <li>• You will review and edit all AI-generated material before publication</li>
                <li>• You understand the limitations of AI-generated content</li>
                <li>• You will comply with all applicable laws and regulations</li>
                <li>• You will respect the intellectual property rights of others</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Updates to This Disclaimer</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground text-sm">
                We may update this disclaimer from time to time to reflect changes in our services or legal
                requirements. Continued use of our services after such changes constitutes acceptance of the updated
                disclaimer.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Contact Us</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-muted-foreground text-sm">
                If you have questions about this disclaimer or our AI-generated content, please contact us at
                support@crea8tools.com
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
